// modules/productTypes.js
export function initProductTypesManagement({ supabaseClient, ui, helpers }) {
  const { ptName, ptAddBtn, ptTbody, ptStatus } = ui;
  const { confirmExact } = helpers;

  let editingId = null;

  function setStatus(msg) {
    if (ptStatus) ptStatus.textContent = msg || "";
  }

  function resetProductTypesScreen() {
    editingId = null;
    setStatus("");
    if (ptName) ptName.value = "";
    if (ptAddBtn) ptAddBtn.textContent = "Add";
    if (ptTbody) ptTbody.innerHTML = "";
  }

  async function loadProductTypes() {
    if (!ptTbody) return;

    setStatus("Loading...");
    ptTbody.innerHTML = "";

    const { data, error } = await supabaseClient
      .from("product_types")
      // IMPORTANT: use PRD codes
      .select("id, type_code2, type_name")
      .order("type_code2", { ascending: true });

    if (error) {
      console.error(error);
      setStatus("Load failed: " + error.message);
      return;
    }

    const rows = data || [];
    if (rows.length === 0) {
      setStatus("No product types found.");
      return;
    }

    setStatus("");

    for (const r of rows) {
      const tr = document.createElement("tr");
      tr.dataset.id = r.id;

      const tdCode = document.createElement("td");
      tdCode.textContent = r.type_code2 || "";

      const tdName = document.createElement("td");
      tdName.textContent = r.type_name || "";

      const tdActions = document.createElement("td");
      tdActions.style.textAlign = "right";

      const editBtn = document.createElement("button");
      editBtn.type = "button";
      editBtn.textContent = "Edit";
      editBtn.addEventListener("click", () => {
        editingId = r.id;
        if (ptName) ptName.value = r.type_name || "";
        if (ptAddBtn) ptAddBtn.textContent = "Save";
        setStatus("Editing — change name then click Save.");
        ptName?.focus();
      });

      const delBtn = document.createElement("button");
      delBtn.type = "button";
      delBtn.className = "btn-danger";
      delBtn.textContent = "Delete";
      delBtn.style.marginLeft = "8px";
      delBtn.addEventListener("click", async () => {
        const ok = await confirmExact(`Delete "${r.type_name}"? This cannot be undone.`);
        if (!ok) return;

        const { data: delData, error: delErr } = await supabaseClient
          .from("product_types")
          .delete()
          .eq("id", r.id)
          .select("id");

        if (delErr) {
          console.error(delErr);
          setStatus("Delete failed: " + delErr.message);
          return;
        }
        if (!delData || delData.length === 0) {
          setStatus("Delete blocked (RLS) — no rows deleted.");
          return;
        }

        if (editingId === r.id) {
          editingId = null;
          if (ptName) ptName.value = "";
          if (ptAddBtn) ptAddBtn.textContent = "Add";
        }

        await loadProductTypes();
      });

      tdActions.appendChild(editBtn);
      tdActions.appendChild(delBtn);

      tr.appendChild(tdCode);
      tr.appendChild(tdName);
      tr.appendChild(tdActions);

      ptTbody.appendChild(tr);
    }
  }

  async function saveProductType() {
    const type_name = (ptName?.value || "").trim();

    if (!type_name) {
      setStatus("Enter Type Name.");
      return;
    }

    // EDIT
    if (editingId) {
      const { data, error } = await supabaseClient
        .from("product_types")
        .update({ type_name })
        .eq("id", editingId)
        .select("id");

      if (error) {
        console.error(error);
        setStatus("Update failed: " + error.message);
        return;
      }
      if (!data || data.length === 0) {
        setStatus("Update blocked (RLS) — no rows updated.");
        return;
      }

      editingId = null;
      if (ptAddBtn) ptAddBtn.textContent = "Add";
      if (ptName) ptName.value = "";
      setStatus("Updated ✅");

      await loadProductTypes();
      return;
    }

    // ADD (code auto-generated by DB trigger)
    const { error } = await supabaseClient
      .from("product_types")
      .insert([{ type_name }]);

    if (error) {
      console.error(error);
      setStatus("Add failed: " + error.message);
      return;
    }

    if (ptName) ptName.value = "";
    setStatus("Added ✅");

    await loadProductTypes();
  }

  function bind() {
    if (ptAddBtn && ptAddBtn.dataset.bound !== "1") {
      ptAddBtn.addEventListener("click", saveProductType);
      ptAddBtn.dataset.bound = "1";
    }
  }

  bind();

  return {
    resetProductTypesScreen,
    loadProductTypes
  };
}
